// Package ghaction generates GitHub Actions workflow files for roborev CI reviews.
package ghaction

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// WorkflowConfig holds the parameters for generating a GitHub Actions workflow.
type WorkflowConfig struct {
	// Agent is the AI agent to use (e.g., "codex", "claude-code", "gemini").
	Agent string

	// Model overrides the default model for the agent.
	Model string

	// ReviewTypes is the list of review types to run (e.g., ["security", "default"]).
	ReviewTypes []string

	// Reasoning is the reasoning level (thorough, standard, fast).
	Reasoning string

	// SecretName is the GitHub Actions secret name that holds the agent API key.
	SecretName string

	// RoborevVersion is the roborev release version to install. Empty means "latest".
	RoborevVersion string
}

// DefaultConfig returns a WorkflowConfig with sensible defaults.
func DefaultConfig() WorkflowConfig {
	return WorkflowConfig{
		Agent:       "codex",
		ReviewTypes: []string{"security"},
		Reasoning:   "thorough",
		SecretName:  "ROBOREV_API_KEY",
	}
}

// agentEnvVar returns the environment variable name that the agent expects
// for API authentication.
func agentEnvVar(agent string) string {
	switch strings.TrimSpace(strings.ToLower(agent)) {
	case "claude-code", "claude":
		return "ANTHROPIC_API_KEY"
	case "gemini":
		return "GOOGLE_API_KEY"
	case "copilot":
		return "GITHUB_TOKEN"
	case "codex", "opencode", "droid":
		return "OPENAI_API_KEY"
	default:
		return "OPENAI_API_KEY"
	}
}

// agentInstallCmd returns the shell command(s) to install the given agent CLI.
func agentInstallCmd(agent string) string {
	switch strings.TrimSpace(strings.ToLower(agent)) {
	case "claude-code", "claude":
		return "npm install -g @anthropic-ai/claude-code"
	case "gemini":
		return "npm install -g @anthropic-ai/claude-code" // placeholder; gemini CLI install varies
	case "copilot":
		return "gh extension install github/gh-copilot || true"
	case "codex":
		return "npm install -g @openai/codex"
	case "opencode":
		return "go install github.com/opencode-ai/opencode@latest"
	case "cursor":
		return "echo 'Cursor agent is not available in CI environments'"
	case "droid":
		return "npm install -g @anthropic-ai/claude-code" // placeholder
	default:
		return fmt.Sprintf("echo 'Unknown agent: %s - install manually'", agent)
	}
}

// Generate produces a GitHub Actions workflow YAML string from the given config.
func Generate(cfg WorkflowConfig) (string, error) {
	if cfg.Agent == "" {
		cfg.Agent = "codex"
	}
	if len(cfg.ReviewTypes) == 0 {
		cfg.ReviewTypes = []string{"security"}
	}
	if cfg.Reasoning == "" {
		cfg.Reasoning = "thorough"
	}
	if cfg.SecretName == "" {
		cfg.SecretName = "ROBOREV_API_KEY"
	}

	data := templateData{
		Agent:           cfg.Agent,
		Model:           cfg.Model,
		ReviewTypes:     cfg.ReviewTypes,
		Reasoning:       cfg.Reasoning,
		SecretName:      cfg.SecretName,
		AgentEnvVar:     agentEnvVar(cfg.Agent),
		AgentInstallCmd: agentInstallCmd(cfg.Agent),
		RoborevVersion:  cfg.RoborevVersion,
	}

	tmpl, err := template.New("workflow").Funcs(template.FuncMap{
		"join": strings.Join,
	}).Parse(workflowTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}

	return buf.String(), nil
}

// WriteWorkflow generates the workflow and writes it to the given path.
// Creates parent directories as needed. Returns an error if the file
// already exists and force is false.
func WriteWorkflow(cfg WorkflowConfig, outputPath string, force bool) error {
	if !force {
		if _, err := os.Stat(outputPath); err == nil {
			return fmt.Errorf("workflow file already exists: %s (use --force to overwrite)", outputPath)
		}
	}

	content, err := Generate(cfg)
	if err != nil {
		return err
	}

	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create directory %s: %w", dir, err)
	}

	if err := os.WriteFile(outputPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("write workflow: %w", err)
	}

	return nil
}

type templateData struct {
	Agent           string
	Model           string
	ReviewTypes     []string
	Reasoning       string
	SecretName      string
	AgentEnvVar     string
	AgentInstallCmd string
	RoborevVersion  string
}

var workflowTemplate = `# roborev CI Review
# Generated by: roborev init gh-action
# Runs AI-powered code reviews on pull requests.
#
# Required setup:
#   1. Add a repository secret named "{{ .SecretName }}" with your agent API key
#   2. The secret is passed as {{ .AgentEnvVar }} to the review agent
#
# Customize review behavior by editing the flags below or adding a
# .roborev.toml file to your repository root.

name: roborev

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install roborev
        run: |
          {{- if .RoborevVersion }}
          ROBOREV_VERSION="{{ .RoborevVersion }}"
          {{- else }}
          ROBOREV_VERSION=$(curl -sL https://api.github.com/repos/roborev-dev/roborev/releases/latest | grep '"tag_name"' | sed -E 's/.*"v?([^"]+)".*/\1/')
          {{- end }}
          curl -sL "https://github.com/roborev-dev/roborev/releases/download/v${ROBOREV_VERSION}/roborev_${ROBOREV_VERSION}_linux_amd64.tar.gz" | tar xz -C /usr/local/bin roborev
          roborev version

      - name: Install agent
        run: {{ .AgentInstallCmd }}

      - name: Run review
        env:
          {{ .AgentEnvVar }}: ${{"{{"}} secrets.{{ .SecretName }} {{"}}"}}
        run: |
          # Review each commit in the PR
          BASE_SHA=${{"{{"}} github.event.pull_request.base.sha {{"}}"}}
          HEAD_SHA=${{"{{"}} github.event.pull_request.head.sha {{"}}"}}

          for COMMIT in $(git rev-list --reverse ${BASE_SHA}..${HEAD_SHA}); do
            echo "Reviewing commit ${COMMIT}..."
            roborev review \
              --agent {{ .Agent }} \
              --reasoning {{ .Reasoning }}{{ if .Model }} \
              --model {{ .Model }}{{ end }} \
              --commit "${COMMIT}" \
              --type {{ join "," .ReviewTypes }} || true
          done

      - name: Post results
        if: always()
        env:
          GH_TOKEN: ${{"{{"}} secrets.GITHUB_TOKEN {{"}}"}}
        run: |
          # Collect review results and post as PR comment
          RESULTS=$(roborev list --format json 2>/dev/null || echo "[]")
          if [ "${RESULTS}" = "[]" ]; then
            echo "No review results to post"
            exit 0
          fi
          roborev comment --pr ${{"{{"}} github.event.pull_request.number {{"}}"}} 2>/dev/null || \
            echo "Note: comment posting requires additional setup"
`
